version: '3.1'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
    healthcheck:
      test: ["CMD-SHELL", "neo4j status"]
      interval: 30s
      timeout: 10s
      retries: 5

